version: '3'
services:
  server1:
    build: ./server1
    ports:
      - "5001:5000"
  server2:
    build: ./server2
    ports:
      - "5002:5000"
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - server1
      - server2 
